apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: scrapercontainer
            image: gcr.io/providence-demo/gkeweatherscraper
