apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: scrapercontainer
            image: gcr.io/providence-demo/gkeweatherscraper
            imagePullPolicy: Always
            env:
            - name: PROJECT_ID
              value: providence-demo
            - name: LOCATION
              value: global
            - name: KEYRING
              value: storage
            - name: KEY
              value: mykey
            - name: ENCRYPTED_BUCKET
              value: mdh-prov-enc-bucket
            - name: SECRET
              value: dark-sky-key
            - name: WEATHER_BUCKET
              value: mdh-weather-bucket